-- colors/colorscheme.lua
vim.opt.background = "dark"
vim.g.colors_name = "roxane"

local colors = {
	-- PATCH_OPEN
Normal = {fg = "#E6E6E6", bg = "#1A1A1A"},
Added = {fg = "#A4EABB"},
BlinkCmpDocCursorLine = {bg = "#30124F"},
BlinkCmpDocSeparator = {fg = "#66616B"},
BlinkCmpGhostText = {fg = "#807986", italic = true},
BlinkCmpKind = {fg = "#4457D5"},
BlinkCmpKindArray = {fg = "#8E9121"},
BlinkCmpKindColor = {fg = "#592191"},
BlinkCmpKindEnum = {fg = "#BB4C2A"},
BlinkCmpKindEnumMember = {fg = "#BB4C2A"},
BlinkCmpKindEvent = {fg = "#B6BB2A"},
BlinkCmpKindFile = {fg = "#732ABB"},
BlinkCmpKindFolder = {fg = "#732ABB"},
BlinkCmpKindKey = {fg = "#66616B"},
BlinkCmpKindKeyword = {fg = "#8C44D5"},
BlinkCmpKindObject = {fg = "#219147"},
BlinkCmpKindReference = {fg = "#4457D5"},
BlinkCmpKindSnippet = {fg = "#8E9121"},
BlinkCmpKindText = {fg = "#CCCCCC"},
BlinkCmpKindTypeParameter = {fg = "#69D5DD"},
BlinkCmpKindUnit = {fg = "#44CBD5"},
BlinkCmpKindValue = {fg = "#E6E6E6"},
BlinkCmpLabel = {fg = "#E6E6E6"},
BlinkCmpLabelDeprecated = {fg = "#BB2A4A", strikethrough = true},
BlinkCmpLabelDescription = {fg = "#66616B"},
BlinkCmpLabelDetail = {fg = "#CCCCCC"},
BlinkCmpLabelMatch = {fg = "#C7A4EA", bold = true},
BlinkCmpScrollBarGutter = {fg = "#19161D"},
BlinkCmpScrollBarThumb = {fg = "#807986"},
BlinkCmpSignatureHelpActiveParameter = {fg = "#592191", bold = true},
BlinkCmpSource = {fg = "#732ABB"},
Boolean = {fg = "#9C7AE1"},
["@boolean"] = {link = "Boolean"},
Changed = {fg = "#807986"},
Comment = {fg = "#808080"},
Constant = {fg = "#E6E6E6"},
["@constant"] = {link = "Constant"},
["@constant.builtin"] = {link = "Constant"},
["@constant.macro"] = {link = "Constant"},
Cursor = {fg = "#1A1A1A", bg = "#E6E6E6"},
CursorLine = {bg = "#2E2834"},
CursorLineNr = {fg = "#A4ADEA"},
DiagnosticError = {fg = "#912139"},
DiagnosticHint = {fg = "#807986"},
DiagnosticInfo = {fg = "#218A91"},
DiagnosticOk = {fg = "#219147"},
DiagnosticSignInfo = {fg = "#8C44D5"},
DiagnosticWarn = {fg = "#8E9121"},
DiffAdd = {fg = "#0E3E1E", bg = "#7AE19C"},
DiffChange = {fg = "#797A6C", bg = "#DDE17A"},
DiffDelete = {fg = "#D1153D", bg = "#E17A90"},
DiffText = {fg = "#44CBD5"},
Directory = {fg = "#732ABB"},
Error = {fg = "#BB2A4A"},
FloatBorder = {fg = "#8C56C2"},
BlinkCmpDocBorder = {link = "FloatBorder"},
BlinkCmpMenuBorder = {link = "FloatBorder"},
BlinkCmpSignatureHelpBorder = {link = "FloatBorder"},
NoiceCmdlinePopupBorder = {link = "FloatBorder"},
NoiceConfirmBorder = {link = "FloatBorder"},
NoicePopupBorder = {link = "FloatBorder"},
NoicePopupmenuBorder = {link = "FloatBorder"},
NoiceSplitBorder = {link = "FloatBorder"},
TelescopeBorder = {link = "FloatBorder"},
FloatFooter = {fg = "#4D4950"},
FloatTitle = {fg = "#A4ADEA"},
Folded = {fg = "#8A8A8A", bg = "#3D3D3D"},
Function = {fg = "#A4ADEA"},
Identifier = {fg = "#E8DAF7"},
["@module"] = {link = "Identifier"},
["@module.builtin"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
["@variable.member"] = {link = "Identifier"},
IncSearch = {fg = "#E6E6E6", bg = "#89689C"},
CurSearch = {link = "IncSearch"},
MatchParen = {link = "IncSearch"},
Search = {link = "IncSearch"},
Substitue = {link = "IncSearch"},
LspKindArray = {fg = "#8E9121"},
LspKindInterface = {link = "LspKindClass"},
LspKindStruct = {link = "LspKindClass"},
LspKindEnum = {fg = "#913B21"},
LspKindEnumMember = {fg = "#BB4C2A"},
LspKindEvent = {fg = "#B6BB2A"},
LspKindFile = {fg = "#732ABB"},
LspKindFolder = {link = "LspKindFile"},
LspKindMethod = {link = "LspKindFunction"},
LspKindKey = {fg = "#66616B"},
LspKindNamespace = {link = "LspKindModule"},
LspKindPackage = {link = "LspKindModule"},
LspKindNull = {fg = "#912139"},
LspKindObject = {fg = "#219147"},
LspKindOperator = {fg = "#472191"},
LspKindField = {link = "LspKindProperty"},
LspKindSnippet = {fg = "#8E9121"},
LspKindText = {fg = "#CCCCCC"},
LspKindTypeParameter = {fg = "#69D5DD"},
LspKindUnit = {fg = "#44CBD5"},
LspKindValue = {fg = "#E6E6E6"},
NoiceCmdlineIcon = {fg = "#4457D5"},
NoiceCmdlinePopupTitle = {fg = "#A4ADEA"},
NoiceCursor = {fg = "#E6E6E6", bg = "#592191"},
NoiceFormatProgressDone = {fg = "#219147"},
NoiceFormatProgressTodo = {fg = "#807986"},
NoiceLspProgressClient = {fg = "#8C44D5"},
NoiceLspProgressSpinner = {fg = "#44CBD5"},
NoiceLspProgressTitle = {fg = "#4457D5"},
NoicePopupmenuMatch = {fg = "#44CBD5"},
NoicePopupmenuSelected = {bg = "#702AB7"},
NoiceScrollbar = {fg = "#26212C"},
NoiceScrollbarThumb = {fg = "#807986"},
NoiceVirtualText = {fg = "#66616B", italic = true},
NormalFloat = {fg = "#E6E6E6", bg = "#242424"},
BlinkCmpDoc = {link = "NormalFloat"},
BlinkCmpMenu = {link = "NormalFloat"},
BlinkCmpSignatureHelp = {link = "NormalFloat"},
NoiceCmdline = {link = "NormalFloat"},
NoiceCmdlinePopup = {link = "NormalFloat"},
NoiceConfirm = {link = "NormalFloat"},
NoiceMini = {link = "NormalFloat"},
NoicePopup = {link = "NormalFloat"},
NoicePopupmenu = {link = "NormalFloat"},
NoiceSplit = {link = "NormalFloat"},
TelescopeNormal = {link = "NormalFloat"},
NormalNC = {fg = "#E6E6E6", bg = "#242424"},
Number = {fg = "#44CBD5"},
Float = {link = "Number"},
["@number"] = {link = "Number"},
["@number.float"] = {link = "Number"},
Operator = {fg = "#9C7AE1"},
BlinkCmpKindOperator = {link = "Operator"},
Pmenu = {fg = "#BA8FE6", bg = "#1A1A1A"},
PmenuSel = {fg = "#E6E6E6", bg = "#BA8FE6"},
PmenuMatch = {link = "PmenuSel"},
PmenuMatchSel = {link = "PmenuSel"},
Question = {fg = "#D28BFE"},
Removed = {fg = "#E68FA2"},
RenderMarkdownBullet = {fg = "#7A2DC8"},
RenderMarkdownTableHead = {fg = "#732ABB"},
RenderMarkdownTableRow = {fg = "#732ABB"},
SnacksPickerDir = {fg = "#A192AF"},
SnacksPickerDirectory = {fg = "#E3D1F5"},
SnacksPickerFile = {fg = "#B4BCEE"},
SnacksPickerListCursorLine = {bg = "#7F6798"},
SnacksPickerTotals = {fg = "#A4ADEA"},
Special = {fg = "#9E61DB"},
SpellBad = {sp = "#BB2A4A", undercurl = true},
SpellCap = {sp = "#B6BB2A", undercurl = true},
SpellLocal = {sp = "#2AB1BB", undercurl = true},
SpellRare = {sp = "#8FE0E6", undercurl = true},
Statement = {fg = "#8C44D5"},
StatusLine = {fg = "#E6E6E6", bg = "#1C1C1C"},
TabLine = {link = "StatusLine"},
String = {fg = "#C7A4EA"},
Character = {link = "String"},
["@comment.documentation"] = {link = "String"},
["@string"] = {link = "String"},
["@string.documetation"] = {link = "String"},
TabLineFill = {fg = "#C7A4EA"},
TabLineSel = {bg = "#732ABB"},
TelescopePreviewBorder = {link = "TelescopeBorder"},
TelescopePromptBorder = {link = "TelescopeBorder"},
TelescopeResultsBorder = {link = "TelescopeBorder"},
WhichKeyBorder = {link = "TelescopeBorder"},
TelescopePreviewNormal = {link = "TelescopeNormal"},
TelescopePromptNormal = {link = "TelescopeNormal"},
TelescopeResultsNormal = {link = "TelescopeNormal"},
TelescopePreviewTitle = {fg = "#A4ADEA"},
TelescopePromptTitle = {fg = "#A4ADEA"},
TelescopeResultsTitle = {fg = "#A4ADEA"},
TelescopeSelection = {fg = "#FFFFFF", bg = "#7F6798"},
TelescopeSelectionCaret = {fg = "#592191"},
Type = {fg = "#DEA4EA"},
["@constructor"] = {link = "Type"},
["@type"] = {link = "Type"},
["@type.builtin"] = {link = "Type"},
Visual = {fg = "#E6E6E6", bg = "#513C5D"},
WhichKey = {fg = "#8F64B9", bg = "#242424"},
WhichKeyDesc = {fg = "#D9C1F1"},
WhichKeyFloat = {fg = "#E6E6E6", bg = "#1A1A1A"},
WhichKeyGroup = {fg = "#C7A4EA", bold = true},
WhichKeyIcon = {fg = "#4457D5"},
WhichKeyIconAzure = {fg = "#44CBD5"},
MiniIconsAzure = {link = "WhichKeyIconAzure"},
WhichKeyIconBlue = {fg = "#7E8BE2"},
MiniIconsBlue = {link = "WhichKeyIconBlue"},
WhichKeyIconCyan = {fg = "#44CBD5"},
MiniIconsCyan = {link = "WhichKeyIconCyan"},
WhichKeyIconGreen = {fg = "#186832"},
MiniIconsGreen = {link = "WhichKeyIconGreen"},
WhichKeyIconGrey = {fg = "#807986"},
MiniIconsGrey = {link = "WhichKeyIconGrey"},
WhichKeyIconOrange = {fg = "#D56644"},
MiniIconsOrange = {link = "WhichKeyIconOrange"},
WhichKeyIconPurple = {fg = "#A369DD"},
MiniIconsPurple = {link = "WhichKeyIconPurple"},
WhichKeyIconRed = {fg = "#D54463"},
MiniIconsRed = {link = "WhichKeyIconRed"},
WhichKeyIconYellow = {fg = "#95974E"},
MiniIconsYellow = {link = "WhichKeyIconYellow"},
WhichKeyNormal = {fg = "#B3B3B3"},
WhichKeySeparator = {fg = "#E6E6E6"},
WhichKeyTitle = {fg = "#734E97", bold = true},
WhichKeyValue = {fg = "#A4ADEA"},
WinSeparator = {fg = "#1C1C1C"},
YankHighlight = {fg = "#1A1A1A", bg = "#A4ADEA", bold = true},
["@attribute"] = {fg = "#807986"},
["@attribute.builtin"] = {link = "@attribute"},
BlinkCmpKindBoolean = {link = "@boolean"},
LspKindBoolean = {link = "@boolean"},
["@comment.error"] = {fg = "#912139"},
["@comment.note"] = {fg = "#44CBD5"},
["@comment.todo"] = {fg = "#592191"},
["@comment.warning"] = {fg = "#8E9121"},
BlinkCmpKindConstant = {link = "@constant"},
LspKindConstant = {link = "@constant"},
BlinkCmpKindConstructor = {link = "@constructor"},
LspKindConstructor = {link = "@constructor"},
["@function.builtin"] = {fg = "#6979DD"},
BlinkCmpKindFunction = {link = "@function.builtin"},
BlinkCmpKindMethod = {link = "@function.builtin"},
LspKindFunction = {link = "@function.builtin"},
["@lsp.mod.abstract"] = {italic = true},
["@lsp.mod.async"] = {fg = "#44CBD5", italic = true},
["@lsp.mod.declaration"] = {bold = true},
["@lsp.mod.defaultLibrary"] = {fg = "#DB61D1"},
["@lsp.mod.definition"] = {},
["@lsp.mod.deprecated"] = {fg = "#BB2A4A", strikethrough = true},
["@lsp.mod.documentation"] = {fg = "#403649"},
["@lsp.mod.modification"] = {fg = "#8E9121"},
["@lsp.mod.readonly"] = {fg = "#E6E6E6", bold = true},
["@lsp.mod.static"] = {fg = "#66616B"},
["@markup.heading"] = {fg = "#C7A4EA", bold = true},
["@markup.heading.1"] = {fg = "#B07EE2", bold = true},
RenderMarkdownH1Bg = {link = "@markup.heading.1"},
["@markup.heading.2"] = {fg = "#D17EE2", bold = true},
RenderMarkdownH2Bg = {link = "@markup.heading.2"},
["@markup.heading.3"] = {fg = "#E27EC1", bold = true},
RenderMarkdownH3Bg = {link = "@markup.heading.3"},
["@markup.heading.4"] = {fg = "#E27E9F", bold = true},
RenderMarkdownH4Bg = {link = "@markup.heading.4"},
["@markup.heading.5"] = {fg = "#E27E8F", bold = true},
RenderMarkdownH5Bg = {link = "@markup.heading.5"},
["@markup.heading.6"] = {fg = "#E28F7E", bold = true},
RenderMarkdownH6Bg = {link = "@markup.heading.6"},
["@markup.link"] = {fg = "#8C44D5"},
["@markup.link.label"] = {fg = "#B2A4EA", underline = true},
["@markup.link.url"] = {fg = "#B3AFB6"},
["@markup.list"] = {fg = "#A4ADEA"},
["@markup.list.checked"] = {fg = "#8C44D5"},
["@markup.list.unchecked"] = {fg = "#A369DD"},
["@markup.math"] = {fg = "#9450D7"},
["@markup.quote"] = {fg = "#A4ADEA"},
["@markup.raw"] = {fg = "#A4ADEA", bg = "#3E4151", bold = true},
["@markup.raw.block"] = {bg = "#262626"},
RenderMarkdownCode = {link = "@markup.raw.block"},
RenderMarkdownCodeInline = {link = "@markup.raw"},
BlinkCmpKindModule = {link = "@module"},
BlinkCmpKindNamespace = {link = "@module"},
BlinkCmpKindPackage = {link = "@module"},
LspKindModule = {link = "@module"},
BlinkCmpKindNumber = {link = "@number"},
LspKindNumber = {link = "@number"},
["@punctuation.special"] = {fg = "#8C44D5"},
["@string.escape"] = {fg = "#592191"},
["@string.regexp"] = {fg = "#D0D544"},
["@string.special.url"] = {fg = "#4457D5"},
BlinkCmpKindString = {link = "@string"},
LspKindString = {link = "@string"},
["@tag"] = {fg = "#A165DC"},
["@tag.builtin"] = {link = "@tag"},
BlinkCmpKindClass = {link = "@type"},
BlinkCmpKindInterface = {link = "@type"},
BlinkCmpKindStruct = {link = "@type"},
LspKindClass = {link = "@type"},
["@variable.builtin"] = {fg = "#891F89"},
BlinkCmpKindField = {link = "@variable.member"},
BlinkCmpKindProperty = {link = "@variable.member"},
LspKindProperty = {link = "@variable.member"},
["@variable.parameter"] = {fg = "#B3AFB6"},
["@variable.parameter.builtin"] = {fg = "#807986"},
BlinkCmpKindVariable = {link = "@variable"},
LspKindVariable = {link = "@variable"},
	-- PATCH_CLOSE
}

vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='roxane'")

for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
