-- colors/colorscheme.lua
vim.opt.background = "dark"
vim.g.colors_name = "codalone"

local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
	Normal = { fg = "#B3B3B3", bg = "#29232F" },
	Added = { fg = "#A4EABB" },
	Boolean = { fg = "#9C7AE1" },
	["@boolean"] = { link = "Boolean" },
	Changed = { fg = "#807986" },
	Comment = { fg = "#A192AF" },
	Constant = { fg = "#E6E6E6" },
	["@constant"] = { link = "Constant" },
	["@constant.builtin"] = { link = "Constant" },
	["@constant.macro"] = { link = "Constant" },
	Cursor = { fg = "#29232F", bg = "#B3B3B3" },
	CursorLine = { bg = "#7F6798" },
	CursorLineNr = { fg = "#A4ADEA" },
	DiagnosticError = { fg = "#912139" },
	DiagnosticHint = { fg = "#807986" },
	DiagnosticInfo = { fg = "#218A91" },
	DiagnosticOk = { fg = "#219147" },
	DiagnosticWarn = { fg = "#8E9121" },
	DiffAdd = { fg = "#0E3E1E" },
	DiffChange = { fg = "#4D4950" },
	DiffDelete = { fg = "#BB2A4A" },
	DiffText = { fg = "#44CBD5" },
	Directory = { fg = "#732ABB" },
	Error = { fg = "#BB2A4A" },
	FloatBorder = { fg = "#260E3E" },
	TelescopeBorder = { link = "FloatBorder" },
	FloatFooter = { fg = "#4D4950" },
	FloatTitle = { fg = "#A4ADEA" },
	Folded = { fg = "#807986", bg = "#260E3E" },
	Function = { fg = "#A4ADEA" },
	Identifier = { fg = "#E8DAF7" },
	["@module"] = { link = "Identifier" },
	["@module.builtin"] = { link = "Identifier" },
	["@variable"] = { link = "Identifier" },
	["@variable.member"] = { link = "Identifier" },
	LspReferenceText = { fg = "#26212C", bg = "#A4ADEA" },
	NormalFloat = { fg = "#B3B3B3", bg = "#2E2735" },
	TelescopeNormal = { link = "NormalFloat" },
	NormalNC = { fg = "#B3B3B3", bg = "#302938" },
	Number = { fg = "#44CBD5" },
	Float = { link = "Number" },
	["@number"] = { link = "Number" },
	["@number.float"] = { link = "Number" },
	Operator = { fg = "#9C7AE1" },
	Pmenu = { fg = "#BA8FE6", bg = "#29232F" },
	PmenuSel = { fg = "#E6E6E6", bg = "#BA8FE6" },
	PmenuMatch = { link = "PmenuSel" },
	PmenuMatchSel = { link = "PmenuSel" },
	Question = { fg = "#A4ADEA" },
	Removed = { fg = "#E68FA2" },
	SnacksPickerDirectory = { fg = "#E3D1F5" },
	SnacksPickerFile = { fg = "#B4BCEE" },
	SnacksPickerListCursorLine = { fg = "#FFFFFF", bg = "#7F6798" },
	SnacksPickerTotals = { fg = "#A4ADEA" },
	Special = { fg = "#9E61DB" },
	SpellBad = { sp = "#BB2A4A", undercurl = true },
	SpellCap = { sp = "#B6BB2A", undercurl = true },
	SpellLocal = { sp = "#2AB1BB", undercurl = true },
	SpellRare = { sp = "#8FE0E6", undercurl = true },
	Statement = { fg = "#8C44D5" },
	StatusLine = { fg = "#4D4950", bg = "#19161D" },
	TabLine = { link = "StatusLine" },
	String = { fg = "#C7A4EA" },
	Character = { link = "String" },
	["@comment.documentation"] = { link = "String" },
	["@string"] = { link = "String" },
	["@string.documetation"] = { link = "String" },
	TabLineFill = { fg = "#C7A4EA" },
	TabLineSel = { bg = "#732ABB" },
	TelescopePreviewBorder = { link = "TelescopeBorder" },
	TelescopePromptBorder = { link = "TelescopeBorder" },
	TelescopeResultsBorder = { link = "TelescopeBorder" },
	TelescopePreviewNormal = { link = "TelescopeNormal" },
	TelescopePromptNormal = { link = "TelescopeNormal" },
	TelescopeResultsNormal = { link = "TelescopeNormal" },
	TelescopePreviewTitle = { fg = "#A4ADEA" },
	TelescopePromptTitle = { fg = "#A4ADEA" },
	TelescopeResultsTitle = { fg = "#A4ADEA" },
	TelescopeSelection = { fg = "#FFFFFF", bg = "#7F6798" },
	TelescopeSelectionCaret = { fg = "#592191" },
	Type = { fg = "#DEA4EA" },
	["@constructor"] = { link = "Type" },
	["@type"] = { link = "Type" },
	["@type.builtin"] = { link = "Type" },
	Visual = { fg = "#E6E6E6", bg = "#A4ADEA" },
	CurSearch = { link = "Visual" },
	IncSearch = { link = "Visual" },
	MatchParen = { link = "Visual" },
	Search = { link = "Visual" },
	Substitue = { link = "Visual" },
	WinSeparator = { fg = "#19161D" },
	YankHighlight = { fg = "#29232F", bg = "#A4ADEA", bold = true },
	["@attribute"] = { fg = "#807986" },
	["@attribute.builtin"] = { link = "@attribute" },
	["@comment.error"] = { fg = "#912139" },
	["@comment.note"] = { fg = "#44CBD5" },
	["@comment.todo"] = { fg = "#592191" },
	["@comment.warning"] = { fg = "#8E9121" },
	["@function.builtin"] = { fg = "#6979DD" },
	["@markup.quote"] = { fg = "#A4ADEA" },
	["@markup.raw"] = { fg = "#A4ADEA" },
	["@punctuation.special"] = { fg = "#8C44D5" },
	["@string.escape"] = { fg = "#592191" },
	["@string.regexp"] = { fg = "#D0D544" },
	["@string.special.url"] = { fg = "#4457D5" },
	["@tag"] = { fg = "#A165DC" },
	["@tag.builtin"] = { link = "@tag" },
	["@variable.builtin"] = { fg = "#891F89" },
	["@variable.parameter"] = { fg = "#B3AFB6" },
	["@variable.parameter.builtin"] = { fg = "#807986" },
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='roxane'")

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
